import type { Metadata } from 'next';
import { LegalPage } from '@/components/legal/LegalPage';

export const metadata: Metadata = {
  title: 'Terms of Service — Kidai',
  description: 'The terms that govern your use of Kidai.',
};

const LAST_UPDATED = 'May 15, 2026';

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" lastUpdated={LAST_UPDATED}>
      <p>
        These Terms govern your use of Kidai (the &ldquo;Service&rdquo;), provided by the makers of Kidai (&ldquo;we&rdquo;,
        &ldquo;us&rdquo;). By using the Service you agree to these Terms.
      </p>

      <h2>Who Can Use the Service</h2>
      <p>
        You must be at least 18 years old and capable of entering into a binding contract. The Service is for parents,
        caregivers, and adult guardians.
      </p>

      <h2>Not Medical, Psychological, or Professional Advice</h2>
      <p>
        Kidai provides informational guidance only. It is not a substitute for professional advice from a pediatrician,
        therapist, psychologist, social worker, or other qualified professional. Do not rely on Kidai for diagnosis or
        treatment. If your child is in danger, harming themselves or others, or experiencing a medical or mental health
        emergency, contact emergency services or a qualified professional immediately.
      </p>

      <h2>AI-Generated Content</h2>
      <p>
        Responses are generated by AI and may be incomplete, inaccurate, or inappropriate for your specific situation. Use
        your own judgment. You are responsible for any actions you take based on guidance from the Service.
      </p>

      <h2>Your Account and Device</h2>
      <p>
        You are responsible for the device you use, for keeping it secure, and for the activity that occurs through the
        Service on your device. The history saved on your device is your responsibility to manage.
      </p>

      <h2>Subscriptions, Trial, and Billing</h2>
      <ul>
        <li>
          Kidai offers a free trial followed by a paid subscription. Subscriptions are billed by Apple through your Apple
          ID and renew automatically unless cancelled at least 24 hours before the end of the current period.
        </li>
        <li>
          You can manage or cancel your subscription in your Apple ID account settings. Refunds, where available, are
          handled by Apple under their policies.
        </li>
        <li>
          Prices may change. If we change the price of a subscription, we&rsquo;ll give you notice and an opportunity to
          cancel before the change takes effect.
        </li>
      </ul>

      <h2>Acceptable Use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use the Service in a way that is unlawful, abusive, or harmful to others.</li>
        <li>Attempt to reverse engineer, decompile, or extract the underlying models or source code, except to the extent allowed by law.</li>
        <li>Use the Service to generate content that exploits, endangers, or sexualizes a minor.</li>
        <li>Resell, sublicense, or share access to the Service.</li>
        <li>Interfere with the Service, probe it for vulnerabilities, or use it to train competing AI models.</li>
      </ul>

      <h2>Content You Provide</h2>
      <p>
        You retain ownership of the recordings, transcripts, and notes you create (&ldquo;Your Content&rdquo;). You grant us a
        limited license to process Your Content solely to operate the Service for you (for example, to transcribe and to
        produce a response). We will not use Your Content to train AI models.
      </p>

      <h2>Intellectual Property</h2>
      <p>
        The Service, including its software, design, copy, and the EFRAT-based framing of responses, is owned by us or our
        licensors and is protected by intellectual property laws. We grant you a personal, revocable, non-transferable license
        to use the Service for its intended purpose.
      </p>

      <h2>Privacy</h2>
      <p>
        Our handling of personal information is described in our <a href="/privacy">Privacy Policy</a>, which is incorporated
        into these Terms.
      </p>

      <h2>Termination</h2>
      <p>
        You may stop using the Service at any time. We may suspend or terminate access if you violate these Terms or if we
        need to protect the Service or its users. Sections that by their nature should survive termination will survive.
      </p>

      <h2>Disclaimers</h2>
      <p>
        THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; WITHOUT WARRANTIES OF ANY KIND, WHETHER
        EXPRESS, IMPLIED, OR STATUTORY, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
        NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR SUITABLE FOR YOUR
        SITUATION.
      </p>

      <h2>Limitation of Liability</h2>
      <p>
        TO THE FULLEST EXTENT PERMITTED BY LAW, WE WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL,
        OR PUNITIVE DAMAGES, OR FOR ANY LOSS OF PROFITS OR DATA, ARISING OUT OF OR RELATED TO YOUR USE OF THE SERVICE. OUR
        TOTAL LIABILITY FOR ANY CLAIM ARISING FROM THE SERVICE WILL NOT EXCEED THE GREATER OF THE AMOUNT YOU PAID US IN THE
        TWELVE MONTHS BEFORE THE CLAIM OR USD $50.
      </p>

      <h2>Indemnification</h2>
      <p>
        You agree to defend and indemnify us against claims arising from your misuse of the Service or your violation of
        these Terms.
      </p>

      <h2>Changes</h2>
      <p>
        We may update these Terms from time to time. If changes are material, we&rsquo;ll update the date at the top and,
        where appropriate, notify you in the app. Continued use after the change means you accept the new Terms.
      </p>

      <h2>Governing Law</h2>
      <p>
        These Terms are governed by the laws of the State of Delaware, USA, without regard to its conflict of laws rules.
        Disputes will be resolved in the state or federal courts located in Delaware, unless applicable law gives you a
        non-waivable right to bring claims elsewhere.
      </p>

      <h2>Contact</h2>
      <p>
        Questions: <a href="mailto:support@kidai.app">support@kidai.app</a>.
      </p>
    </LegalPage>
  );
}
